// Mock data for sidebar leagues and countries (Waliyabet style)
export const leagues = [
  { name: 'Premier League', count: 15 },
  { name: 'Bundesliga', count: 13 },
  { name: 'LaLiga', count: 18 },
  { name: 'Serie A', count: 18 },
  { name: 'Ligue 1', count: 8 },
  { name: 'All Leagues', count: 0 },
];

export const countries = [
  { name: 'Algeria', count: 5 },
  { name: 'Argentina', count: 10 },
  { name: 'Armenia', count: 2 },
  { name: 'Australia', count: 10 },
  { name: 'Austria', count: 15 },
  { name: 'Austria Amateur', count: 20 },
  { name: 'Azerbaijan', count: 3 },
  { name: 'Belarus', count: 4 },
  { name: 'Belgium', count: 11 },
  { name: 'Bosnia & Herzegovina', count: 10 },
  { name: 'Brazil', count: 56 },
  { name: 'Bulgaria', count: 20 },
  { name: 'Canada', count: 4 },
  { name: 'Chile', count: 12 },
  { name: 'China', count: 3 },
  { name: 'Colombia', count: 14 },
  { name: 'Costa Rica', count: 4 },
  { name: 'Croatia', count: 16 },
  { name: 'Cyprus', count: 5 },
  { name: 'Czechia', count: 46 },
  { name: 'Denmark', count: 7 },
  { name: 'Ecuador', count: 7 },
  { name: 'Egypt', count: 7 },
  { name: 'El Salvador', count: 5 },
  { name: 'England', count: 17 },
  { name: 'England Amateur', count: 7 },
  { name: 'Estonia', count: 5 },
  { name: 'Faroe Islands', count: 2 },
  { name: 'Finland', count: 8 },
  { name: 'France', count: 26 },
  { name: 'Georgia', count: 3 },
  { name: 'Germany', count: 21 },
  { name: 'Germany Amateur', count: 12 },
  { name: 'Greece', count: 14 },
  { name: 'Guatemala', count: 6 },
  { name: 'Honduras', count: 5 },
  { name: 'Hong Kong, China', count: 2 },
  { name: 'Hungary', count: 16 },
  { name: 'Iceland', count: 12 },
  { name: 'Indonesia', count: 3 },
  { name: 'International', count: 36 },
  { name: 'International Clubs', count: 20 },
  { name: 'Ireland', count: 9 },
  { name: 'Israel', count: 14 },
  { name: 'Italy', count: 57 },
  { name: 'Ivory Coast', count: 1 },
  { name: 'Japan', count: 20 },
  { name: 'Kazakhstan', count: 1 },
  { name: 'Kosovo', count: 2 },
  { name: 'Latvia', count: 5 },
  { name: 'Lithuania', count: 11 },
  { name: 'Luxembourg', count: 5 },
  { name: 'Mexico', count: 21 },
  { name: 'Moldova', count: 4 },
  { name: 'Netherlands', count: 21 },
  { name: 'New Zealand', count: 4 },
  { name: 'Nicaragua', count: 3 },
  { name: 'North Macedonia', count: 2 },
  { name: 'Norway', count: 15 },
  { name: 'Panama', count: 5 },
  { name: 'Paraguay', count: 10 },
  { name: 'Peru', count: 7 },
  { name: 'Poland', count: 42 },
  { name: 'Portugal', count: 37 },
  { name: 'Qatar', count: 2 },
  { name: 'Republic of Korea', count: 13 },
  { name: 'Romania', count: 26 },
  { name: 'Russia', count: 28 },
  { name: 'San Marino', count: 4 },
  { name: 'Saudi Arabia', count: 3 },
  { name: 'Scotland', count: 13 },
  { name: 'Serbia', count: 12 },
  { name: 'Slovakia', count: 20 },
  { name: 'Slovenia', count: 12 },
  { name: 'South Africa', count: 5 },
  { name: 'Spain', count: 29 },
  { name: 'Sweden', count: 35 },
  { name: 'Switzerland', count: 11 },
  { name: 'Thailand', count: 8 },
  { name: 'Turkiye', count: 16 },
  { name: 'Turkiye Amateur', count: 7 },
  { name: 'Ukraine', count: 4 },
  { name: 'United Arab Emirates', count: 4 },
  { name: 'Uruguay', count: 13 },
  { name: 'USA', count: 32 },
  { name: 'Venezuela', count: 8 },
  { name: 'Wales', count: 1 },
];
